on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build Nuxt image
        run: |
          docker build \
          --tag ghcr.io/$GITHUB_ACTOR/geo-to-csv:$(echo $GITHUB_SHA | head -c7) \
          --tag ghcr.io/$GITHUB_ACTOR/geo-to-csv:latest \
          .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push image to GitHub
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/geo-to-csv:$(echo $GITHUB_SHA | head -c7)
          docker push ghcr.io/$GITHUB_ACTOR/geo-to-csv:latest
